### ISSUE TITLE
Channel Menu

### ISSUE THREAD

**Issue by lapadapdap** [Murray-Bridge-Bunyips/BunyipBellower#1]
Things TODO:

- ~~Have messages render and position correctly~~
- ~~Make a proper menu containing all channels, with CSS styled buttons~~
- ~~Displays names correctly~~
- ~~Scrolls when too many channels are present~~

optional:
- Remembers what channel the user was last in when reloading
- New messages notices
- Checks for what channels the user can access

**Comment by bubner** [comment]
Left todo:
New messages per channel, not focusing on permissions unless needed.
