### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by bubner** [Murray-Bridge-Bunyips/BunyipBellower#2]
- Message metadata attachment, make it look prettier
- Add sound when notification is triggered
- Consider in-app notifications (maybe *just* the sound? perhaps check document.hasFocus() to send notifications instead of the hidden system)

**Comment by lapadapdap** [comment]
An addition to this could be having a temporary Do Not Disturb mode, as well as a time out where notifications won't be sent for a little bit perhaps.
